### PR TITLE
Support more ENV vars and dotenv

### PR DESCRIPTION
**Pull request by tadpol**
Added these ENV variables matching to the similar argument options.
- EXO_CONFIG
- EXO_HTTPTIMEOUT
- EXO_USERAGENT
- EXO_PORTALS
- EXO_VENDORTOKEN
- EXO_VENDOR

With dotenv, you can put those into a .env file in the working directory that you're running exoline from.

### CODE REVIEW

**Comment by dweaver** [comment]
Any chance you could make this work with Python 2.6? python-dotenv uses OrderedDict, which isn't supported in 2.6.

```
======================================================================
ERROR: Failure: ImportError (cannot import name OrderedDict)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/danw/prj/exosite/exoline/.tox/py26/lib/python2.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/danw/prj/exosite/exoline/.tox/py26/lib/python2.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/danw/prj/exosite/exoline/.tox/py26/lib/python2.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/danw/prj/exosite/exoline/test/test.py", line 31, in <module>
    from exoline import exo
  File "/Users/danw/prj/exosite/exoline/exoline/exo.py", line 73, in <module>
    from dotenv import load_dotenv
  File "/Users/danw/prj/exosite/exoline/.tox/py26/lib/python2.6/site-packages/dotenv.py", line 6, in <module>
    from collections import OrderedDict
ImportError: cannot import name OrderedDict
```

It looks like [this one](https://github.com/pedroburon/dotenv) supports Python 2.6.

**Comment by tadpol** [comment]
New pull at #118
